services:
  app:
    image: argos-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  helios-db:
    container_name: helios-db
    image: postgres:12.20-alpine3.20
    ports:
      - "5100:5432"
    environment:
      POSTGRES_DB: helios
      POSTGRES_USER: phaeton
      POSTGRES_PASSWORD: ecliptic
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
